"use strict";
const cfg=window.APP_CONFIG||{};
const ROTATE_MS=10000;
let lastCallKey="",audioEnabled=false,audioCtx=null,loading=false,latestData=null,lastRotateAt=Date.now();
let nextPage=0,workPages={RECEIVING_IN_PROGRESS:0,WAITING_DOCUMENT_RETURN:0,WAITING_GATE_OUT:0};
const $=id=>document.getElementById(id);
document.addEventListener("DOMContentLoaded",init);
function init(){
  $("soundButton")?.addEventListener("click",enableSound);$("fullButton")?.addEventListener("click",toggleFull);
  document.addEventListener("fullscreenchange",()=>{if($("fullButton"))$("fullButton").innerHTML=document.fullscreenElement?"<span>⛶</span> ออกจากเต็มหน้าจอ":"<span>⛶</span> เต็มหน้าจอ"});
  tick();setInterval(tick,1000);loadQueue();setInterval(loadQueue,5000);
  setInterval(()=>{if(latestData&&Date.now()-lastRotateAt>=ROTATE_MS){rotatePages();lastRotateAt=Date.now()}},1000);
}
function tick(){const now=new Date(),tz=cfg.timezone||"Asia/Bangkok";$("queueDate").textContent=new Intl.DateTimeFormat("th-TH",{timeZone:tz,weekday:"long",day:"numeric",month:"short",year:"numeric"}).format(now);$("queueClock").textContent=new Intl.DateTimeFormat("en-GB",{timeZone:tz,hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:false}).format(now)}
async function loadQueue(){if(loading)return;loading=true;try{const base=String(cfg.apiBaseUrl||"").replace(/\/$/,"");if(!base)throw new Error("ไม่พบที่อยู่ระบบ");const r=await fetch(base+"/api/public/queue",{cache:"no-store"});const data=await r.json();if(!r.ok||data.success===false)throw new Error(data.message||"โหลดข้อมูลไม่สำเร็จ");latestData=data;render(data);health(true)}catch(e){health(false,e.message)}finally{loading=false}}
function render(data){renderCall(data.calling);renderSummary(data);renderNext(data);renderWork(data);$("updatedAt").textContent="อัปเดตล่าสุด "+formatTime(data.generatedAt)}
function renderSummary(data){const c=data.counts||{},defs=[["👥","คิวรอตรวจรับ",c.READY_FOR_RECEIVING||0,"ready"],["☑","กำลังตรวจรับ",c.RECEIVING_IN_PROGRESS||0,"progress"],["▤","รอรับเอกสารคืน",c.WAITING_DOCUMENT_RETURN||0,"return"],["🚚","รอออกจากพื้นที่",c.WAITING_GATE_OUT||0,"out"]];$("summaryCards").innerHTML=defs.map(([icon,label,n,tone])=>`<article class="summary-${tone}"><span class="summary-icon">${icon}</span><small>${label}</small><b>${Number(n).toLocaleString("th-TH")}</b><em>คัน</em></article>`).join("")}
function renderCall(item){const panel=$("callPanel"),doorBox=$("callDoorBox");if(!item){panel.classList.add("idle");$("callNumber").textContent="รอการเรียกคิว";$("callCompany").textContent="–";$("callPlate").textContent="–";$("callDoor").textContent="–";doorBox.hidden=false;$("callInstructionPrefix").textContent="กรุณาตรวจสอบสถานะคิว";$("callInstruction").textContent="รอการเรียกคิว";return}panel.classList.remove("idle");$("callNumber").textContent=item.appointmentNo||"–";$("callCompany").textContent=item.companyName||"ไม่ระบุบริษัท";$("callPlate").textContent=plateText(item);$("callDoor").textContent=item.doorCode||"–";doorBox.hidden=!item.doorCode;$("callInstructionPrefix").textContent="กรุณาเข้ารับการตรวจรับ";$("callInstruction").textContent=item.doorCode?`ที่ประตู ${item.doorCode}`:"ได้ทันที";const key=[item.appointmentNo,item.receivingStartedAt].join(":");if(key!==lastCallKey){lastCallKey=key;nextPage=0;Object.keys(workPages).forEach(k=>workPages[k]=0);lastRotateAt=Date.now();panel.classList.remove("flash");void panel.offsetWidth;panel.classList.add("flash");if(audioEnabled)beep()}}
function readyItems(data){return(data.items||[]).filter(x=>x.status==="READY_FOR_RECEIVING").sort((a,b)=>(a.stageSince||0)-(b.stageSince||0))}
function renderNext(data){const items=readyItems(data),size=6,pages=Math.max(1,Math.ceil(items.length/size));if(nextPage>=pages)nextPage=0;const start=nextPage*size,shown=items.slice(start,start+size);$("nextPageLabel").textContent=items.length?(pages>1?`หน้า ${nextPage+1}/${pages} · ${items.length} คัน`:`${items.length} คัน`):"ไม่มีคิวรอ";$("nextQueue").innerHTML=shown.length?shown.map((item,i)=>nextItem(item,start+i+1)).join(""):`<div class="queue-empty">ไม่มีรถรอตรวจรับ</div>`;$("rotationLabel").textContent=pages>1?`คิวถัดไป ${nextPage+1}/${pages}`:""}
function nextItem(item,order){return`<article class="next-item"><div class="order">${order}</div><div class="next-appt">${esc(item.appointmentNo)}</div><div class="next-company">${esc(item.companyName||"ไม่ระบุบริษัท")}</div><div class="next-plate">${esc(plateText(item))}</div><div class="next-wait">${shortDuration(item.elapsedSeconds)}</div></article>`}
function renderWork(data){const all=data.items||[],defs=[["กำลังตรวจรับ","RECEIVING_IN_PROGRESS","progress"],["รอรับเอกสารคืน","WAITING_DOCUMENT_RETURN","return"],["รอออกจากพื้นที่","WAITING_GATE_OUT","out"]];let total=0;$("workGroups").innerHTML=defs.map(([label,status,tone])=>{const items=all.filter(x=>x.status===status).sort((a,b)=>(a.stageSince||0)-(b.stageSince||0));total+=items.length;const size=4,pages=Math.max(1,Math.ceil(items.length/size));if((workPages[status]||0)>=pages)workPages[status]=0;const page=workPages[status]||0,shown=items.slice(page*size,page*size+size);return`<section class="work-group tone-${tone}"><header><h3>${label}</h3><b>${items.length} คัน${pages>1?` · ${page+1}/${pages}`:""}</b></header><div class="work-body">${shown.length?shown.map(workItem).join(""):`<p class="work-empty">ไม่มีรายการ</p>`}</div></section>`}).join("");$("workCount").textContent=`${total.toLocaleString("th-TH")} คัน`}
function workItem(item){return`<article class="work-item"><b>${esc(item.appointmentNo)}</b><span class="work-company">${esc(item.companyName||"ไม่ระบุบริษัท")}</span><small>${esc(plateText(item))}${item.doorCode?` · ประตู ${esc(item.doorCode)}`:""}</small></article>`}
function rotatePages(){if(!latestData)return;const ready=readyItems(latestData),npages=Math.ceil(ready.length/6);if(npages>1)nextPage=(nextPage+1)%npages;const all=latestData.items||[];for(const status of Object.keys(workPages)){const pages=Math.ceil(all.filter(x=>x.status===status).length/4);if(pages>1)workPages[status]=(workPages[status]+1)%pages}renderNext(latestData);renderWork(latestData)}
function plateText(item){const p=String(item.vehiclePlate||"").trim(),prov=String(item.province||"").trim();return[p,prov].filter(Boolean).join(" ")||"ไม่ระบุทะเบียน"}
function health(ok,msg=""){const el=$("queueHealth");el.classList.toggle("error",!ok);el.textContent=ok?"● พร้อมใช้งาน":"● เชื่อมต่อไม่ได้";el.title=msg}
function shortDuration(sec){sec=Math.max(0,Math.floor(Number(sec)||0));const h=Math.floor(sec/3600),m=Math.floor((sec%3600)/60);return h?`${h} ชม. ${m} นาที`:`${m} นาที`}
function formatTime(sec){if(!sec)return"–";return new Intl.DateTimeFormat("en-GB",{timeZone:cfg.timezone||"Asia/Bangkok",hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:false}).format(new Date(Number(sec)*1000))}
function esc(v){return String(v??"").replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'\"':"&quot;","'":"&#39;"}[c]))}
async function enableSound(){audioEnabled=!audioEnabled;$("soundButton").innerHTML=audioEnabled?"<span>🔊</span> เปิดเสียงแล้ว":"<span>🔇</span> ปิดเสียง";if(audioEnabled){audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();await audioCtx.resume().catch(()=>{});beep()}}
function beep(){try{audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.value=880;g.gain.setValueAtTime(.001,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.16,audioCtx.currentTime+.02);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+.34);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+.37)}catch{}}
async function toggleFull(){try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{}}
