"use strict";
const cfg=window.APP_CONFIG||{};const stages=[
 {id:"WAITING_DOCUMENT_SUBMISSION",label:"รอยื่นเอกสาร",tone:"tone-doc"},
 {id:"READY_FOR_RECEIVING",label:"พร้อมตรวจรับ",tone:"tone-ready"},
 {id:"RECEIVING_IN_PROGRESS",label:"กำลังตรวจรับ",tone:"tone-progress"},
 {id:"WAITING_DOCUMENT_RETURN",label:"รอรับเอกสารคืน",tone:"tone-return"},
 {id:"WAITING_GATE_OUT",label:"รอออกจากพื้นที่",tone:"tone-out"}
];let lastCallKey="",audioEnabled=false,audioCtx=null,loading=false;
const $=id=>document.getElementById(id);document.addEventListener("DOMContentLoaded",init);
function init(){$("soundButton").addEventListener("click",enableSound);$("fullButton").addEventListener("click",toggleFull);document.addEventListener("fullscreenchange",()=>$("fullButton").textContent=document.fullscreenElement?"ออกจากเต็มหน้าจอ":"เต็มหน้าจอ");tick();setInterval(tick,1000);loadQueue();setInterval(loadQueue,3000)}
function tick(){const now=new Date(),d=new Intl.DateTimeFormat("th-TH",{timeZone:cfg.timezone||"Asia/Bangkok",weekday:"long",day:"numeric",month:"long",year:"numeric"}).format(now),t=new Intl.DateTimeFormat("en-GB",{timeZone:cfg.timezone||"Asia/Bangkok",hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:false}).format(now);$("queueDate").textContent=d;$("queueClock").textContent=t;document.querySelectorAll("[data-stage-since]").forEach(el=>el.textContent=shortDuration(Date.now()/1000-Number(el.dataset.stageSince)))}
async function loadQueue(){if(loading)return;loading=true;try{const base=String(cfg.apiBaseUrl||"").replace(/\/$/,"");if(!base)throw new Error("ไม่พบที่อยู่ระบบ");const r=await fetch(base+"/api/public/queue",{cache:"no-store"});const data=await r.json();if(!r.ok||data.success===false)throw new Error(data.message||"โหลดข้อมูลไม่สำเร็จ");render(data);health(true)}catch(e){health(false,e.message)}finally{loading=false}}
function render(data){renderCall(data.calling);$("summaryCards").innerHTML=stages.map(s=>`<article class="${s.tone}"><i class="summary-dot"></i><div><small>${s.label}</small><b>${Number(data.counts?.[s.id]||0).toLocaleString("th-TH")} <small>คัน</small></b></div></article>`).join("");$("queueColumns").innerHTML=stages.map(s=>{const items=(data.items||[]).filter(x=>x.status===s.id);return`<section class="queue-column ${s.tone}"><header><h2>${s.label}</h2><b>${items.length}</b></header><div class="queue-list">${items.length?items.map(item=>queueItem(item)).join(""):`<div class="queue-empty">ไม่มีรายการ</div>`}</div></section>`}).join("");$("updatedAt").textContent="อัปเดต "+formatTime(data.generatedAt);$("buildLabel").textContent=""}
function renderCall(item){const panel=$("callPanel");if(!item){panel.classList.add("idle");$("callNumber").textContent="รอการเรียกคิว";$("callCompany").textContent="เมื่อพนักงานเริ่มตรวจรับ รายการจะขึ้นที่นี่";$("callDoor").textContent="";$("callNote").textContent="กรุณาตรวจสอบสถานะของหมายเลขนัดหมาย";return}panel.classList.remove("idle");$("callNumber").textContent=item.appointmentNo;$("callCompany").textContent=item.companyName;$("callDoor").textContent=item.doorCode?`ประตู ${item.doorCode}`:"";$("callNote").textContent=item.doorCode?`กรุณาเข้ารับการตรวจรับที่ประตู ${item.doorCode}`:"กรุณาเข้ารับการตรวจรับ";const key=[item.appointmentNo,item.receivingStartedAt].join(":");if(key!==lastCallKey){lastCallKey=key;panel.classList.remove("flash");void panel.offsetWidth;panel.classList.add("flash");if(audioEnabled)beep()}}
function queueItem(item){return`<article class="queue-item"><b>${esc(item.appointmentNo)}</b><small>${item.doorCode?`ประตู ${esc(item.doorCode)}`:""}</small><span class="company">${esc(item.companyName)}</span><small>รอ <span data-stage-since="${Number(item.stageSince||0)}">${shortDuration(item.elapsedSeconds)}</span></small></article>`}
function health(ok,msg=""){const el=$("queueHealth");el.classList.toggle("error",!ok);el.textContent=ok?"● พร้อมใช้งาน":"● เชื่อมต่อไม่ได้";el.title=msg}
function shortDuration(sec){sec=Math.max(0,Math.floor(Number(sec)||0));const h=Math.floor(sec/3600),m=Math.floor((sec%3600)/60);return h?`${h} ชม. ${m} นาที`:`${m} นาที`}
function formatTime(sec){if(!sec)return"–";return new Intl.DateTimeFormat("en-GB",{timeZone:cfg.timezone||"Asia/Bangkok",day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:false}).format(new Date(Number(sec)*1000)).replace(",","")}
function esc(v){return String(v??"").replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
async function enableSound(){audioEnabled=!audioEnabled;$("soundButton").textContent=audioEnabled?"🔔 เปิดเสียงแล้ว":"🔕 ปิดเสียง";if(audioEnabled){audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();await audioCtx.resume().catch(()=>{});beep()}}
function beep(){try{audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.value=880;g.gain.setValueAtTime(.001,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.18,audioCtx.currentTime+.02);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+.35);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+.38)}catch{}}
async function toggleFull(){try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{}}
