"use strict";
const cfg=window.APP_CONFIG||{};
const PAGE_SIZE=8,ROTATE_MS=12000;
let lastCallKey="",audioEnabled=false,audioCtx=null,loading=false,nextPage=0,lastRotateAt=Date.now(),latestData=null;
const $=id=>document.getElementById(id);
document.addEventListener("DOMContentLoaded",init);
function init(){
  $("soundButton").addEventListener("click",enableSound);$("fullButton").addEventListener("click",toggleFull);
  document.addEventListener("fullscreenchange",()=>$("fullButton").textContent=document.fullscreenElement?"ออกจากเต็มหน้าจอ":"เต็มหน้าจอ");
  tick();setInterval(tick,1000);loadQueue();setInterval(loadQueue,5000);
  setInterval(()=>{if(latestData&&Date.now()-lastRotateAt>=ROTATE_MS){rotateNextPage();lastRotateAt=Date.now()}},1000);
}
function tick(){const now=new Date(),d=new Intl.DateTimeFormat("th-TH",{timeZone:cfg.timezone||"Asia/Bangkok",weekday:"long",day:"numeric",month:"long",year:"numeric"}).format(now),t=new Intl.DateTimeFormat("en-GB",{timeZone:cfg.timezone||"Asia/Bangkok",hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:false}).format(now);$("queueDate").textContent=d;$("queueClock").textContent=t;document.querySelectorAll("[data-stage-since]").forEach(el=>el.textContent=shortDuration(Date.now()/1000-Number(el.dataset.stageSince)))}
async function loadQueue(){if(loading)return;loading=true;try{const base=String(cfg.apiBaseUrl||"").replace(/\/$/,"");if(!base)throw new Error("ไม่พบที่อยู่ระบบ");const r=await fetch(base+"/api/public/queue",{cache:"no-store"});const data=await r.json();if(!r.ok||data.success===false)throw new Error(data.message||"โหลดข้อมูลไม่สำเร็จ");latestData=data;render(data);health(true)}catch(e){health(false,e.message)}finally{loading=false}}
function render(data){renderCall(data.calling);renderSummary(data);renderNext(data);renderWork(data);$("updatedAt").textContent="อัปเดต "+formatTime(data.generatedAt);$("buildLabel").textContent=""}
function renderSummary(data){const c=data.counts||{};const defs=[
 ["คิวรอตรวจรับ",c.READY_FOR_RECEIVING||0,"ready"],["กำลังตรวจรับ",c.RECEIVING_IN_PROGRESS||0,"progress"],["รอรับเอกสารคืน",c.WAITING_DOCUMENT_RETURN||0,"return"],["รอออกจากพื้นที่",c.WAITING_GATE_OUT||0,"out"]
];$("summaryCards").innerHTML=defs.map(([label,n,tone])=>`<article class="summary-${tone}"><small>${label}</small><b>${Number(n).toLocaleString("th-TH")}</b><span>คัน</span></article>`).join("")}
function renderCall(item){const panel=$("callPanel");if(!item){panel.classList.add("idle");$("callNumber").textContent="รอการเรียกคิว";$("callCompany").textContent="เมื่อพนักงานเริ่มตรวจรับ รายการจะขึ้นที่นี่";$("callPlate").textContent="–";$("callDoor").textContent="–";$("callNote").textContent="กรุณาตรวจสอบสถานะของหมายเลขนัดหมาย";return}panel.classList.remove("idle");$("callNumber").textContent=item.appointmentNo;$("callCompany").textContent=item.companyName;$("callPlate").textContent=plateText(item);$("callDoor").textContent=item.doorCode||"–";$("callNote").textContent=item.doorCode?`กรุณาเข้ารับการตรวจรับที่ประตู ${item.doorCode}`:"กรุณาเข้ารับการตรวจรับ";const key=[item.appointmentNo,item.receivingStartedAt].join(":");if(key!==lastCallKey){lastCallKey=key;nextPage=0;lastRotateAt=Date.now();panel.classList.remove("flash");void panel.offsetWidth;panel.classList.add("flash");if(audioEnabled)beep()}}
function renderNext(data){const items=(data.items||[]).filter(x=>x.status==="READY_FOR_RECEIVING").sort((a,b)=>(a.stageSince||0)-(b.stageSince||0));const pages=Math.max(1,Math.ceil(items.length/PAGE_SIZE));if(nextPage>=pages)nextPage=0;const start=nextPage*PAGE_SIZE,shown=items.slice(start,start+PAGE_SIZE);$("nextPageLabel").textContent=items.length?`แสดง ${start+1}–${Math.min(start+PAGE_SIZE,items.length)} จาก ${items.length}`:"ไม่มีคิวรอ";$("nextQueue").innerHTML=shown.length?shown.map((item,i)=>nextItem(item,start+i+1)).join(""):`<div class="queue-empty">ไม่มีรถรอตรวจรับ</div>`}
function rotateNextPage(){if(!latestData)return;const items=(latestData.items||[]).filter(x=>x.status==="READY_FOR_RECEIVING");const pages=Math.ceil(items.length/PAGE_SIZE);if(pages<=1)return;nextPage=(nextPage+1)%pages;renderNext(latestData)}
function nextItem(item,order){return`<article class="next-item"><div class="order">${order}</div><div class="next-main"><b>${esc(item.appointmentNo)}</b><span>${esc(item.companyName)}</span><small>${esc(plateText(item))}</small></div><div class="next-side"><b>${item.doorCode?`ประตู ${esc(item.doorCode)}`:""}</b><small>รอ <span data-stage-since="${Number(item.stageSince||0)}">${shortDuration(item.elapsedSeconds)}</span></small></div></article>`}
function renderWork(data){const all=data.items||[];const defs=[
 ["กำลังตรวจรับ","RECEIVING_IN_PROGRESS","progress",5],["รอรับเอกสารคืน","WAITING_DOCUMENT_RETURN","return",4],["รอออกจากพื้นที่","WAITING_GATE_OUT","out",3]
];let total=0;$("workGroups").innerHTML=defs.map(([label,status,tone,limit])=>{const items=all.filter(x=>x.status===status).sort((a,b)=>(a.stageSince||0)-(b.stageSince||0));total+=items.length;const shown=items.slice(0,limit);return`<section class="work-group tone-${tone}"><header><h3>${label}</h3><b>${items.length}</b></header><div>${shown.length?shown.map(workItem).join(""):`<p class="work-empty">ไม่มีรายการ</p>`}${items.length>limit?`<p class="more">และอีก ${items.length-limit} คัน</p>`:""}</div></section>`}).join("");$("workCount").textContent=`${total.toLocaleString("th-TH")} คัน`}
function workItem(item){return`<article class="work-item"><div><b>${esc(item.appointmentNo)}</b><span>${esc(item.companyName)}</span><small>${esc(plateText(item))}</small></div><div class="work-side"><b>${item.doorCode?esc(item.doorCode):""}</b><small><span data-stage-since="${Number(item.stageSince||0)}">${shortDuration(item.elapsedSeconds)}</span></small></div></article>`}
function plateText(item){const p=String(item.vehiclePlate||"").trim(),prov=String(item.province||"").trim();return [p,prov].filter(Boolean).join(" ")||"ไม่ระบุทะเบียน"}
function health(ok,msg=""){const el=$("queueHealth");el.classList.toggle("error",!ok);el.textContent=ok?"● พร้อมใช้งาน":"● เชื่อมต่อไม่ได้";el.title=msg}
function shortDuration(sec){sec=Math.max(0,Math.floor(Number(sec)||0));const h=Math.floor(sec/3600),m=Math.floor((sec%3600)/60);return h?`${h} ชม. ${m} นาที`:`${m} นาที`}
function formatTime(sec){if(!sec)return"–";return new Intl.DateTimeFormat("en-GB",{timeZone:cfg.timezone||"Asia/Bangkok",day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:false}).format(new Date(Number(sec)*1000)).replace(",","")}
function esc(v){return String(v??"").replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
async function enableSound(){audioEnabled=!audioEnabled;$("soundButton").textContent=audioEnabled?"🔔 เปิดเสียงแล้ว":"🔕 ปิดเสียง";if(audioEnabled){audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();await audioCtx.resume().catch(()=>{});beep()}}
function beep(){try{audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.value=880;g.gain.setValueAtTime(.001,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.18,audioCtx.currentTime+.02);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+.35);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+.38)}catch{}}
async function toggleFull(){try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{}}
